### ISSUE TITLE
the number of bugs in this software is too damn high

### ISSUE THREAD

**Issue by ghost** [EESI/PyFeast#2]
am i the only one around here who hates ldconfig?
if you could fix this bug, that'd be great

who put bugs in this software? 'aliens'

python -c 'import feast'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "feast.py", line 24, in <module>
    libFSToolbox = c.CDLL("libFSToolbox.so"); 
  File "/usr/lib/python2.7/ctypes/**init**.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libFSToolbox.so: undefined symbol: checkedCalloc

so there's that

**Comment by Craigacp** [comment]
Do you need to import libMIToolbox too? I'm not entirely sure how the loading works for Python code, but the checkedCalloc symbol is in libMIToolbox.

**Comment by ghost** [comment]
No I don't think so, ld should handle loading the library dependencies, and
not that ther error wasn't that it couldn't load libMItoolbox (which i
think would happen if  ld couldnt find it, rather than the one function
being missing)

**Comment by Craigacp** [comment]
You should check if this is fixed by Craigacp/FEAST#2. I had the linker arguments in the wrong order for FEAST.
